language: node_js
node_js:
  - 'node'
  - '10'
  - '12'
services:
 - mongodb
addons:
  code_climate:
    repo_token: 'd6589258f9a1e18f8dc6e4c1700d960c00298e1a8618bb9cde99ceaaded49398'
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
