language: node_js
node_js:
  - '12'
services:
 - mongodb
addons:
  code_climate:
    repo_token: 25d4b7c087cd2e8ffba443cdfa3726157ec35b90e9e3cffced34268964f8bf4a
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
